### ISSUE TITLE
Regarding language

### ISSUE THREAD

**Issue by Monsberg** [angelleye/woocommerce-price-per-word#22]
This plugin works perfect. Thanks.
However, I need a small language adjustement, I want to open a little proof reading business and the shop is in Denmark. I need "Price" to be "pris" and "price per word" to be "pris pr. ord". "Total Price" should be "total pris".
Is there anywhere I can make the change myself?

**Comment by angelleye** [comment]
Are you familiar with working with POT files for localization of plugins?  There is a default .pot file in the /languages folder.

**Comment by Monsberg** [comment]
I have worked a little bit with Poedit, but I have not worked with an empty .pot file. But I guess I can learn :-)
