### ISSUE TITLE
Price Breaks

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#27]
User request:  https://wordpress.org/support/topic/maximum-words-at-a-certain-price?replies=1

>Is it possible to set multiple prices for multiple levels, i.e. one price up to 3,000 words and then another price from 3,001 to 10,000, and then another price for 10,000 to infinity? As an alternative to an absolute word cap. And as an alternative to just taking what I get.

**Comment by keyurptl** [comment]
@angelleye I did not get it properly, where we need to set these price breaks functionality. Whether we need to set it for global configuration or individual product. So please suggest the proper path.

**Comment by angelleye** [comment]
This will be a product level option similar to what we're doing with #37.  Then we'll need to include this in the bulk edit tool we're building in #38 so that people can easily set this for multiple products at once if they want to.

**Comment by keyurptl** [comment]
@angelleye I have implemented the price breaks functionality for simple product only. Please review it.

**Comment by angelleye** [comment]
The validation message for the price field needs to be improved.  Right now it's not formatted well...

![image](https://cloud.githubusercontent.com/assets/629241/17394173/4c700852-59ed-11e6-8802-8efbb0649a13.png)

**Comment by angelleye** [comment]
Also, for some reason I cannot set a price value.  As soon as I set a value and move away from the field the value disappears, so I can't even save it.

**Comment by angelleye** [comment]
Need to adjust the alert message verbiage.


1) The last max field value must be greather than 0 to add more row.

The Max {words/characters} field for the last row must be greater than 0 to add an additional row.

2) The Last max field must be greather than min value.

The Max {words/characters} for the last row must be greater than the Min {words/characters}, or use the > symbol.

3) Max field must be greather than min value.

The Max {words/characters} field must be greater than the Min {words/characters} field.

4) Note: Next all rows is reseting.

All rows will be reset to match new value.
