### ISSUE TITLE
Same file different formats returning different word counts..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#29]
User report:  https://wordpress.org/support/topic/number-of-words-varies-according-to-the-file-type?replies=1#post-7955295

**Comment by lauracrespo** [comment]
Hello, I need this plugin to work by March, 30. I just want to know if you are still working on this plugin or not anymore. I see nothing has been done since almost a month and I am concerned. Thanks.

**Comment by angelleye** [comment]
@lauracrespo Sorry for the delay.  This plugin is not nearly as popular as our others, so it's been a while since we've been able to focus on it.

We are working on the next update for it right now, actually, but we are unable to reproduce this problem.  If you're still interested in working with us on this plugin it would be great if you could provide a copy of the document you were using when this was happening.
