### ISSUE TITLE
Price Per Word label filter / translation..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#32]
User reporting that they'd like to change "Price Per Word" to just say "Per Word" so that it would display like ".10 Per Word" on the site.  So all they need to do is remove the word Price.

I'm thinking we could add a filter hook for this, or I'm also thinking it should work via translation file, but the user is having issues.

Need to review this post:  https://wordpress.org/support/topic/change-price-per-word-to-something-else?replies=9#post-8378505

Then figure out the best way to accomplish this goal and get it working.

**Comment by keyurptl** [comment]
Here is the code snippet to change the label of price.

Hook name : ppw_change_html_label_of_price 

`add_filter('ppw_change_html_label_of_price', 'change_html_label_of_price',1);

function change_html_label_of_price($tag) {
    return "per Word:";
}`

**Comment by keyurptl** [comment]
Sorry i forgot to check the product type, So I added one more param $type in apply_filters() function.

The code snippet is 

Hook name : ppw_change_html_label_of_price

`add_filter('ppw_change_html_label_of_price', 'change_html_label_of_price', 10, 2);`

`function change_html_label_of_price($tag, $type) {
if ($type == 'Word') {
return "per Word:";
} else if ($type == 'Character') {
return "per Character:";
}
else{
return "per Word:";
}
}`

**Comment by aesthete20** [comment]
Where do I add this filter?

**Comment by aesthete20** [comment]
I've found it, don't worry
