### ISSUE TITLE
Bulk Edit Tool

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#38]
In #37 we create a product level option that we need easy access to adjusting within multiple products.

We need to create a bulk edit tool just like we did in Offers for WooCommerce and PayPal for WooCommerce, but of course this one would be for the product settings specific to this plugin (which as of now is only the option covered in #37)

**Comment by keyurptl** [comment]
[Added Bulk Edit Tool under setting menu
- Enable Price per Words action
- Enable Price per Characters action
- Disable Price per Words/Characters action,ref #38 ](https://github.com/angelleye/woocommerce-price-per-word/commit/dbb8fa72d80dcfdfd35667295feac2bc3ed6fd12)
