### ISSUE TITLE
Variable Pricing Display Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#43]
Right now when we enter the variable product display on the front end of the site it only shows us the default pricing for the product.  Switching between the variations doesn't affect the price displayed until after we've uploaded a doc.  Then it shows the total and the price per word/character that was used, and that display does update when you change the drop down option.

We need the primary price to update, though, instead of displaying a secondary price like we are.

**Comment by angelleye** [comment]
I may want to re-address this issue, and maybe #45 as well.

I've noticed that with other variable products, the main pricing displayed for the product shows the range.  For example, it might show $10.00 - $20.00.

For some reason with our variable price per word products it's only showing the first price.  That is why we created this issue and #45, but now that I notice that I think we may have been doing more than necessary.

We just need to figure out why the pricing only shows the first (lowest) price for our product type instead of showing the whole range like other variable products do.

**Comment by keyurptl** [comment]
Hi @angelleye 
I have fixed the range issue, but when you select any option from select box it also changing the range as you selected.
for example :

Price Per Word: $1.00–$2.00
if i select first option from select box and that variant having $1.00 price then range is displaying like $1.00–$1.00

**Comment by angelleye** [comment]
Why are our price per word products acting differently than other products?

**Comment by keyurptl** [comment]
Okay, so i will implement it the same way Woo-commerce do for variable products.

**Comment by mathieubrimbela** [comment]
Hi, delete button (file) is not working with this correction and total price is not updated when i change the drop down option. I'm on WC 3.0.8.
Thanks for all
