### ISSUE TITLE
VAT Display bug..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#47]
> Working with the plugin I discovered another issue. Once the plugin is activated the suffix for the VAT (incl. / excl.) doesn’t appear anymore (see image attached without plugin).
> 
> ![image](https://cloud.githubusercontent.com/assets/629241/18423504/2d30e1ae-786b-11e6-8dee-79243436a82e.png)

**Comment by tejasm-itpath** [comment]
@angelleye 
It is showing suffix of the VAT
https://www.screencast.com/t/cnEOAkLDnB
