### ISSUE TITLE
PDF word count not working

### ISSUE THREAD

**Issue by spartie17** [angelleye/woocommerce-price-per-word#52]
Hi there!

Thank you so much for this plugin, I've been looking for something like this for a long time!

I've just installed it on my site, but I've come across an error when uploading a PDF. I've tried 3 different PDF's and none of them reflect the correct word count. I've attached one as an example. This particular PDF has approximately 1400 words, but when I upload it on the product page it says it only has 200 words.

Thank you so much for all the time and effort you've put into this plugin, I really appreciate it! If you could let me know your progress on this issue, or if you need anymore information regarding the problem please get in touch.

Thank you so much,
Jess

[NZ Content.pdf](https://github.com/angelleye/woocommerce-price-per-word/files/591005/NZ.Content.pdf)

**Comment by angelleye** [comment]
Hmmm, that's odd.  We've had reports of the count being not entirely accurate, but never by that much.  We'll play with this PDF and see what we find.  Thanks for the feedback.

**Comment by tejasm-itpath** [comment]
@angelleye  Yes this happened to sample PDF. with some other PDF it working properly. So something we have to find.
