### ISSUE TITLE
User reported issue.

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#58]
* https://www.angelleye.com/support/scp/tickets.php?id=887

**Comment by tejasm-itpath** [comment]
@angelleye  Assign me to this ticket.

**Comment by angelleye** [comment]
@tejasm-itpath I assigned you to that ticket.  You actually should be able to view them without being assigned, though.  It would just be responding and managing the ticket that you would need to be assigned for.  It's not even letting you read?

**Comment by tejasm-itpath** [comment]
@angelleye  without assign, it shows me **Access Denied to this Ticket** message.

**Comment by tejasm-itpath** [comment]
@angelleye  
This issues already fixed in #43 Variable Products compatibility.  
Price and flow both coming properly with plugin activated and without plugin activated. 
I have tested this with Storefront theme and Divi theme.
