### ISSUE TITLE
WordCount Failure

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#65]
* https://mail.google.com/mail/u/0/#inbox/15fe7153245365ed

Doc is not getting counted correctly.  Doc shows 2867 words while the plugin is counting 3072 words..??

[¿ Ha fracasado el socialismo -PCE (r).docx](https://github.com/angelleye/woocommerce-price-per-word/files/1519606/Ha.fracasado.el.socialismo.-PCE.r.docx)

**Comment by tejasm-itpath** [comment]
@angelleye 
#52  and #64  Both are solved in this commit.

**Comment by tejasm-itpath** [comment]
@angelleye 
#29  #31  #39 Also solved in this commit.
