### ISSUE TITLE
Label needs to say "words" instead of "items"...

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#66]
* https://mail.google.com/mail/u/0/#inbox/15fe926d946406d6

>The main things I would like with your plugin is to change the word from 'items' to 'words' for the word count when it's added to the shopping cart.

**Comment by tejasm-itpath** [comment]
@angelleye  I am not seeing any label like "Items" in Cart page from our plugin.

**Comment by angelleye** [comment]
I asked the user to provide more info on this.  Closing it for now.
