### ISSUE TITLE
Spacing adjustment in our settings panel.

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#68]
We need to adjust our settings tab/label:

![image](https://user-images.githubusercontent.com/629241/33754822-ba467598-dbb3-11e7-92ec-cb7672d825f7.png)

Notice how the others are all nicely aligned, and the label has some space between it and the icon.  Our label is smashed right up next to our icon.  Need it to be spaced to match the others.

**Comment by angelleye** [comment]
@tejasm-itpath Looks good when Price per Word is selected, but if I switch to Price Per Character the label updates, and it's no longer properly spaced/aligned...

![image](https://user-images.githubusercontent.com/629241/33756263-471f2c34-dbba-11e7-9c78-8b808bd4ee56.png)

**Comment by tejasm-itpath** [comment]
@angelleye  sorry , I forgot to change code in JS.
