### ISSUE TITLE
3 decimal issue

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#70]
In #44 we added compatibility for 3 decimal pricing, however, it's rounding the price and displaying the rounded value on the product page instead of the actual price.

Also need to make sure our calculation is using the correct price and not a rounded value.

**Comment by tejasm-itpath** [comment]
@angelleye  This things are not working properly in the Variation products.

**Comment by angelleye** [comment]
@tejasm-itpath What does that mean?  You need more time to resolve it there, or you can't..??

**Comment by tejasm-itpath** [comment]
@angelleye  Need more time :(
