### ISSUE TITLE
Option to hide the QTY field / word count on "price per word" products.

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#71]
Need to add an option in the plugin settings where users can choose to hide the QTY field / word count of the uploaded doc so that only the calculated price gets displayed.

**Comment by angelleye** [comment]
@tejasm-itpath Did you also make sure to hide the QTY/count on the cart page, email receipts, etc. when this option is enabled?

**Comment by tejasm-itpath** [comment]
@angelleye 
Yes , It will hide from Cart page , Order Page in Front End. It will show to admin side in back end in Order Details.
