### ISSUE TITLE
Doc Type Problems

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#8]
I'm having different problems when attempting to upload different doc types.

DOC and DOCX are working as expected, However...

When I upload a PDF everything seems to work except for the price calculation...

![image](https://cloud.githubusercontent.com/assets/629241/10013145/49dd0cc4-60d4-11e5-9775-7a2d19173b16.png)

When I upload a TXT file this is what I get...

![image](https://cloud.githubusercontent.com/assets/629241/10013175/9b3e02e4-60d4-11e5-8fa6-f1e012548e38.png)

**Comment by kcppdevelopers** [comment]
it seems to working fine, please check latest code <a href="http://kcppdevelopers.angelleye.com/product/sample-ppw/"> here</a>

**Comment by angelleye** [comment]
TXT files seem to be working fine for me now, but I am still getting the same result with PDF from woo.angelleye.com with latest code as well as kcppdevelopers.angelleye.com.  When I upload PDF to kcppdev...

![image](https://cloud.githubusercontent.com/assets/629241/10115363/f1420940-63c9-11e5-9ce7-1b6e2ebbe9ac.png)

**Comment by kcppdevelopers** [comment]
I have checked and found secured PDF file is not working.

**Comment by angelleye** [comment]
It makes sense that a secured PDF won't be compatible.  So, I see that you've added an error handler for this scenario, right?

Make sure you see my comment in the [commit](https://github.com/angelleye/woocommerce-price-per-word/commit/82695ee7c3abc1f8047622d7e9ba9c7d95ba92ae).

**Comment by angelleye** [comment]
I've pulled the latest changes, but something isn't right.

Now when I upload any PDF at all I get the message that it's secure or empty even if it's not.  Then it automatically redirects me to the cart with that item added at a single word's price.  

If I upload a DOC file it works as expected, but it also automatically redirects to the cart page.  That wasn't happening before.
