### ISSUE TITLE
Order Receipt Page Adjustments

### ISSUE THREAD

**Issue by angelleye** [angelleye/woocommerce-price-per-word#9]
When the order is completed with uploaded items, the full File Url is being displayed...

![image](https://cloud.githubusercontent.com/assets/629241/10013280/a8d6d89e-60d5-11e5-8911-cdced9fcca4f.png)

We should just show the file name here instead of the full path.

I would then like to make the Type, Total Words, and File Name fields closer together so they are not so spaced out like they are now.

The order receipt looks good with the spacing, but I'd like to make sure it's only displaying the file name there as well.  

Of course, in the admin panel, we could still show the full path, or at least make the file name a link to the full path so that we can easily download the doc.

**Comment by kcppdevelopers** [comment]
I have make the file name a link to the full path so that we can easily download the doc, but regarding space it's woo default structure. if I make it closer then it will conflict with other wordpress themes.

**Comment by angelleye** [comment]
Only thing now is that since we are only displaying the file name instead of the full URL we should change the label to just say File Name instead of File Url.

![image](https://cloud.githubusercontent.com/assets/629241/10115412/e1d416b8-63cb-11e5-88d4-d0bf7ee0e871.png)
